run:
  go: '1.19'
linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
  govet:
    check-shadowing: true
linters:
  enable:
    - dupl
    - errorlint
    - gocritic
    - gosec
    - govet
    - maligned
    - sqlclosecheck
issues:
output:
  # Sort results by: filepath, line and column.
  sort-results: true
